name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install project requirements
      run: poetry install
    - name: Run black
      run: poetry run black --check --diff .
    - name: Run isort
      run: poetry run isort --check --diff .
    - name: Run tests
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        DC_ID: ${{ secrets.DC_ID }}
        DC_ADDRESS: ${{ secrets.DC_ADDRESS }}
        DC_PORT: ${{ secrets.DC_PORT }}
      run: poetry run pytest --cov=session_keeper --cov-report=term-missing
