# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tox
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        DC_ID: ${{ secrets.DC_ID }}
        DC_ADDRESS: ${{ secrets.DC_ADDRESS }}
        DC_PORT: ${{ secrets.DC_PORT }}
      run: |
        tox

        twine upload dist/*
